### ISSUE TITLE
CSS Module 和 CSS-in-JS

### ISSUE THREAD

**Issue by LittlehorseXie** [LittlehorseXie/blog#7]
## 1. 一些问题

原生css自身缺憾

- 不能够嵌套书写，不利于模块开发，语法不够强大
- 没有变量和逻辑上的复用机制，难以维护

面对以上问题，css预处理器给出了可行的解决方案

- 提供变量，利于多处修改
- 增加作用域，使css模块化
- 支持嵌套
- 支持整块逻辑复用

## 2. 之前的解决方案

- BEM
- sass、less

#### 局部作用域
之后构建工具会将类名生成一个哈希字符串
```css
/* style.css  */

.title {  
 color: green;
}
```
```javascript
/* index.js */

import style from "./style.css"

element.innerHTML = '<div class="' + styles.title + '">'
```
最终生成
```css
._3zyde4l1yATCOkgn-DBWEL {
 color: green;
}
```
#### 全局作用域

使用:global(.className)的语法，声明一个全局规则。凡是这样声明的class，都不会被编译成哈希字符串。
```css
.title {
  color: red;
}

:global(.title) {
  color: green;
}
```
使用普通的class的写法，就会引用全局class
```javascript
import React from 'react';
import styles from './App.css';

export default () => {
  return (
    <h1 className="title">
      Hello World
    </h1>
  );
};
```
CSS Modules 还提供一种显式的局部作用域语法:local(.className)，等同于.className，
所以上面的App.css也可以写成下面这样。
```css
:local(.title) {
  color: red;
}

:global(.title) {
  color: green;
}
```
#### 定制哈希类名
css-loader默认的哈希算法是[hash:base64]，这会将.title编译成._3zyde4l1yATCOkgn-DBWEL这样的字符串。

webpack.config.js里面可以定制哈希字符串的格式。
```json
{
  module: {
    loaders: [
    // ...
      {
        test: /\.css$/,
        loader: "style-loader!css-loader?modules&localIdentName=[path][name]---[local]---[hash:base64:5]"
      },
    ]
  }
}
```

#### 组合 Composition
```css
.className {
  color: green;
  background: red;
}

.otherClassName {
  composes: className;
  color: yellow;
}
```
也可以继承其他文件的类规则
```css
.otherClassName {
  composes: className from "./style.css";
}
```
#### 输入变量
CSS Modules 支持使用变量，不过需要安装 PostCSS 和 postcss-modules-values。

```css
/* colors.css */
@value blue: #0c77f8;
@value red: #ff0000;
@value green: #aaf200;
```
``` css
/* App.css */
@value colors: "./colors.css";
@value blue, red, green from colors;

.title {
  color: red;
  background-color: blue;
}
```
